### ISSUE TITLE
Binding on state containing JSON-object does not works anymore

### ISSUE THREAD

**Issue by cdellasanta** [ioBroker/ioBroker.vis#343]
**Describe the bug:**
Binding to an state containing a JSON object does not works anymore with version 1.3.7
Downgrading to version 1.3.6 works again.

**Steps to Reproduce:**
- Create state and set a JSON object as value: e.g.: `{"Sort by":"Sortieren nach","Filter by":"Filtern nach","Device":"Gerät"}`
- Extract a value of the JSON object by key in the view:
   e.g.: `{t:0_userdata.0.vis.unifiNetworkState.translations; t['Sort by'] || 'Sort by'}`

**Error reported in console:**
```
vis.js:2498 Error in eval[value]     : {t:0_userdata.0.vis.unifiNetworkState.translations; t['Sort by'] || 'Sort by'}
vis.js:2499 Error in eval[script]: var t = JSON.parse("{"Sort by":"Sortieren nach","Filter by":"Filtern nach","Device":"Gerät"}");return  
t['Sort by'] || 'Sort by';
vis.js:2500 Error in eval[error] : SyntaxError: missing ) after argument list
```

**Versions:**
Adapter version: vis: 1.3.7
JS-Controller version: 3.1.6 
Node version: v12.20.1
Operating system: linux

**Additional context:**
Caused by https://github.com/ioBroker/ioBroker.vis/pull/333 , I've posted a possible solution of the problem there.

**Comment by cdellasanta** [comment]
Can someone please give a feedback on this?

I'm still blocked to version 1.3.6 because of this. 
I need at least a workaround.

**Comment by cdellasanta** [comment]
### I've found a workaround by myself

Solution is to pass the JSON string such as it won't be affected by this **bug**.

`base64` encode the JSON string -> pass to the state value -> `base64` decode on frontend.

In the frontend I can use Javascript `atob`, but in backend `btoa` is is not available, therefore I've written a global function:

```Javascript
function btoa(string) {
    // REF: https://stackoverflow.com/questions/246801/how-can-you-encode-a-string-to-base64-in-javascript
    // It might sound wired, but we have to use 'ascii' to get the 'utf8' chars to be encoded/decoded correctly

    return Buffer.from(string, 'ascii').toString('base64');
}
``` 

Now I've to write the JSON in the state as follows:
```Javascript
setState(
   '0_userdata.0.vis.unifiNetworkState.translations',
    btoa(JSON.stringify({"Sort by":"Sortieren nach","Filter by":"Filtern nach","Device":"Gerät"})),
    true
);
```

And in frontend, get the value through:
```
{t:0_userdata.0.vis.unifiNetworkState.translations; JSON.parse(atob(t))['Sort by']}
```

This makes the code a bit wired, but permits me to bypass the current problem.

**Comment by Apollon77** [comment]
I think this is the only way. In fact states can only have native datatypes. In the past you could set anslo an object, but in fact it was iunsure what the "read value" is. Also with js-controller 3.3 we much more enforce correct types
